# Generated by Django 4.1.3 on 2022-12-20 19:48

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1_name', models.CharField(max_length=50)),
                ('banner1_link', models.CharField(max_length=50)),
                ('banner1_image', models.ImageField(upload_to='banner1')),
                ('banner1_des', models.CharField(max_length=50)),
                ('banner1_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='banner3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner3_link', models.CharField(max_length=100)),
                ('banner3_image', models.ImageField(upload_to='banner3')),
                ('banner3_deal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='banner4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner4_name', models.CharField(max_length=100)),
                ('banner4_image', models.ImageField(upload_to='banner4')),
                ('banner4_deal', models.CharField(max_length=100)),
                ('banner4_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='banner5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner5_name', models.CharField(max_length=100)),
                ('banner5_image', models.ImageField(upload_to='banner5')),
                ('banner5_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='banner6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner6_name', models.CharField(max_length=100)),
                ('banner6_image', models.ImageField(upload_to='banner6')),
                ('banner6_deal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_first', models.ImageField(upload_to='brand')),
                ('brand_second', models.ImageField(upload_to='brand')),
                ('brand_three', models.ImageField(upload_to='brand')),
                ('brand_four', models.ImageField(upload_to='brand')),
                ('brand_five', models.ImageField(upload_to='brand')),
                ('brand_six', models.ImageField(upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_price', models.CharField(max_length=50)),
                ('feature_image', models.ImageField(upload_to='feature')),
                ('feature_discount', models.CharField(max_length=50)),
                ('feature_oprice', models.CharField(max_length=50)),
                ('feature_list1', models.CharField(max_length=50)),
                ('feature_list2', models.CharField(max_length=50)),
                ('feature_list3', models.CharField(max_length=50)),
                ('feature_list4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feature1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_name', models.CharField(max_length=50)),
                ('feature1_price', models.CharField(max_length=50)),
                ('feature1_image', models.ImageField(upload_to='feature1')),
                ('feature1_discount', models.CharField(max_length=50)),
                ('feature1_oprice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('product_details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.IntegerField()),
                ('product_discount', models.IntegerField()),
                ('product_qty', models.IntegerField()),
                ('product_availability', models.IntegerField()),
                ('product_des', ckeditor_uploader.fields.RichTextUploadingField()),
                ('product_tag', models.CharField(max_length=100)),
                ('product_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recommended1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended1_name', models.CharField(max_length=50)),
                ('recommended1_price', models.CharField(max_length=50)),
                ('recommended1_image', models.ImageField(upload_to='recommended1')),
                ('recommended1_discount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_name', models.CharField(max_length=50)),
                ('selling_price', models.CharField(max_length=50)),
                ('selling_image', models.ImageField(upload_to='selling')),
                ('selling_discount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.main')),
            ],
        ),
        migrations.CreateModel(
            name='threeimag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
        migrations.CreateModel(
            name='sub_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_main')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_main'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.section'),
        ),
        migrations.CreateModel(
            name='additional1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
