# Generated by Django 4.1.3 on 2022-12-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner1_banner3_banner4_banner5_banner6_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_qty',
            new_name='quantity',
        ),
    ]
